### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [atomic14/esp32-pdm-audio#1]
Hello!

I found this project from https://hackaday.com/2024/01/06/no-dac-try-pdm/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by cgreening** [comment]
Closed by https://github.com/atomic14/esp32-pdm-audio/commit/be02adf2dcb36b891f21580c65150bf26719a19e

**Comment by vazhnov** [comment]
"The Unlicense" — amazing! Thank you!
